### ISSUE TITLE
namespace 

### ISSUE THREAD

**Issue by vikasgubbi** [christhomas/kubernetes-cluster#7]
can hostpath namespace and the pod namespace should be same or different will work.

**Comment by christhomas** [comment]
Yes. If you look at my GitHub repo. You will find that I have the hostpath-provisioner in kube-system and then I host volumes in any namespace I want

**Comment by vikasgubbi** [comment]
My question is, if i deploy my custom app in default namespace will it take it take hostpath provisor setup  in kube-system namespace.

**Comment by christhomas** [comment]
That's exactly what I just said and it's what I did with gitlab. So you should find it works ok

**Comment by vikasgubbi** [comment]
Thanks for confirming
